version: '2'
services:
  jenkins-app:
    image: jenkins
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:mysql://jenkins-mysql:3306/jenkins?useUnicode=true&characterEncoding=utf8&useSSL=false
      - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
    ports:
      - 9080:9080
  jenkins-mysql:
    extends:
      file: mysql.yml
      service: jenkins-mysql
